language: node_js
node_js:
   - "8"
cache:
  directories:
  - $HOME/.npm
script:
  - npm test
  - CI="" npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "develop.nich19302.com"
    endpoint: "s3-website-us-west-2.amazonaws.com"
    local_dir: build
    skip_cleanup: true
    region: ap-southeast-2
    on:
      repo: Klezca/Deployment-Prototyping
      branch: develop
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "aws-js-en-deploy-prod"
    local_dir: build
    skip_cleanup: true
    region: ap-southeast-2
    on:
      repo: Klezca/Deployment-Prototyping
      branch: master
