language: node_js
node_js:
   - "8"
cache:
  directories:
  - $HOME/.npm
script:
  - npm test
  - CI="" npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "aws-js-deploy-test"
  skip_cleanup: true
  acl: public_read
  region: ap-southeast-2
  on:
    repo: Klezca/js-dev-en
    branch: master
